export const baseLegacy = {
  other: {
    text: {
      inverse: { value: { base: '{colors.gray.light.100}', _dark: '{colors.gray.dark.100}' } },
    },
  },
  common: {
    '1': { value: { base: '{colors.gray.light.100}', _dark: '{colors.gray.dark.100}' } },
    '2': { value: { base: '{colors.gray.light.200}', _dark: '{colors.gray.dark.200}' } },
    '3': { value: { base: '{colors.gray.light.300}', _dark: '{colors.gray.dark.300}' } },
    '4': { value: { base: '{colors.gray.light.400}', _dark: '{colors.gray.dark.400}' } },
    '5': { value: { base: '{colors.gray.light.500}', _dark: '{colors.gray.dark.500}' } },
    '6': { value: { base: '{colors.gray.light.600}', _dark: '{colors.gray.dark.600}' } },
    '7': { value: { base: '{colors.gray.light.1200}', _dark: '{colors.gray.dark.1200}' } },
    '8': { value: { base: '{colors.black.a1200}', _dark: '{colors.white.a1200}' } },
    '9': { value: { base: '{colors.black.a1100}', _dark: '{colors.white.a1100}' } },
    '10': { value: { base: '{colors.gray.light.1000}', _dark: '{colors.gray.dark.1000}' } },
    '11': { value: { base: '{colors.gray.light.1100}', _dark: '{colors.gray.dark.1100}' } },
    '12': { value: { base: '{colors.gray.light.1200}', _dark: '{colors.gray.dark.1200}' } },
    a1: { value: { base: '{colors.gray.light.a100}', _dark: '{colors.gray.dark.a100}' } },
    a2: { value: { base: '{colors.gray.light.a200}', _dark: '{colors.gray.dark.a200}' } },
    a3: { value: { base: '{colors.gray.light.a300}', _dark: '{colors.gray.dark.a300}' } },
    mediumBg: {
      normal: {
        value: { base: '{colors.gray.light.900}', _dark: '{colors.gray.dark.900}' },
      },
    },
  },
  warning: {
    '1': { value: { base: '{colors.orange.light.100}', _dark: '{colors.orange.dark.100}' } },
    '2': { value: { base: '{colors.orange.light.200}', _dark: '{colors.orange.dark.400}' } },
    '3': { value: { base: '{colors.orange.light.300}', _dark: '{colors.orange.dark.300}' } },
    '4': { value: { base: '{colors.orange.light.400}', _dark: '{colors.orange.dark.200}' } },
    '5': { value: { base: '{colors.orange.light.500}', _dark: '{colors.orange.dark.500}' } },
    '6': { value: { base: '{colors.orange.light.600}', _dark: '{colors.orange.dark.600}' } },
    '7': { value: { base: '{colors.orange.light.700}', _dark: '{colors.orange.dark.900}' } },
    '8': { value: { base: '{colors.orange.light.800}', _dark: '{colors.orange.dark.800}' } },
    '9': { value: { base: '{colors.orange.light.900}', _dark: '{colors.orange.dark.700}' } },
    '10': { value: { base: '{colors.orange.light.1000}', _dark: '{colors.orange.dark.1000}' } },
    '11': { value: { base: '{colors.orange.light.1100}', _dark: '{colors.orange.dark.1100}' } },
    '12': { value: { base: '{colors.orange.light.1200}', _dark: '{colors.orange.dark.1200}' } },
    a1: { value: { base: '{colors.orange.light.a100}', _dark: '{colors.orange.dark.a100}' } },
    a2: { value: { base: '{colors.orange.light.a200}', _dark: '{colors.orange.dark.a200}' } },
    a3: { value: { base: '{colors.orange.light.a300}', _dark: '{colors.orange.dark.a300}' } },
    mediumBg: {
      normal: {
        value: { base: '{colors.orange.light.650}', _dark: '{colors.orange.dark.1000}' },
      },
    },
  },
  info: {
    '1': { value: { base: '{colors.blue.light.100}', _dark: '{colors.blue.dark.100}' } },
    '2': { value: { base: '{colors.blue.light.200}', _dark: '{colors.blue.dark.400}' } },
    '3': { value: { base: '{colors.blue.light.300}', _dark: '{colors.blue.dark.300}' } },
    '4': { value: { base: '{colors.blue.light.400}', _dark: '{colors.blue.dark.200}' } },
    '5': { value: { base: '{colors.blue.light.500}', _dark: '{colors.blue.dark.500}' } },
    '6': { value: { base: '{colors.blue.light.600}', _dark: '{colors.blue.dark.600}' } },
    '7': { value: { base: '{colors.blue.light.700}', _dark: '{colors.blue.dark.900}' } },
    '8': { value: { base: '{colors.blue.light.800}', _dark: '{colors.blue.dark.800}' } },
    '9': { value: { base: '{colors.blue.light.900}', _dark: '{colors.blue.dark.700}' } },
    '10': { value: { base: '{colors.blue.light.1000}', _dark: '{colors.blue.dark.1000}' } },
    '11': { value: { base: '{colors.blue.light.1100}', _dark: '{colors.blue.dark.1100}' } },
    '12': { value: { base: '{colors.blue.light.1200}', _dark: '{colors.blue.dark.1200}' } },
    a1: { value: { base: '{colors.blue.light.a100}', _dark: '{colors.blue.dark.a100}' } },
    a2: { value: { base: '{colors.blue.light.a200}', _dark: '{colors.blue.dark.a200}' } },
    a3: { value: { base: '{colors.blue.light.a300}', _dark: '{colors.blue.dark.a300}' } },
  },
  success: {
    '1': { value: { base: '{colors.green.light.100}', _dark: '{colors.green.dark.100}' } },
    '2': { value: { base: '{colors.green.light.200}', _dark: '{colors.green.dark.400}' } },
    '3': { value: { base: '{colors.green.light.300}', _dark: '{colors.green.dark.300}' } },
    '4': { value: { base: '{colors.green.light.400}', _dark: '{colors.green.dark.200}' } },
    '5': { value: { base: '{colors.green.light.500}', _dark: '{colors.green.dark.500}' } },
    '6': { value: { base: '{colors.green.light.600}', _dark: '{colors.green.dark.600}' } },
    '7': { value: { base: '{colors.green.light.700}', _dark: '{colors.green.dark.900}' } },
    '8': { value: { base: '{colors.green.light.800}', _dark: '{colors.green.dark.800}' } },
    '9': { value: { base: '{colors.green.light.900}', _dark: '{colors.green.dark.700}' } },
    '10': { value: { base: '{colors.green.light.1000}', _dark: '{colors.green.dark.1000}' } },
    '11': { value: { base: '{colors.green.light.1100}', _dark: '{colors.green.dark.1100}' } },
    '12': { value: { base: '{colors.green.light.1200}', _dark: '{colors.green.dark.1200}' } },
    a1: { value: { base: '{colors.green.light.a100}', _dark: '{colors.green.dark.a100}' } },
    a2: { value: { base: '{colors.green.light.a200}', _dark: '{colors.green.dark.a200}' } },
    a3: { value: { base: '{colors.green.light.a300}', _dark: '{colors.green.dark.a300}' } },
  },
  error: {
    '1': { value: { base: '{colors.red.light.100}', _dark: '{colors.red.dark.100}' } },
    '2': { value: { base: '{colors.red.light.200}', _dark: '{colors.red.dark.400}' } },
    '3': { value: { base: '{colors.red.light.300}', _dark: '{colors.red.dark.300}' } },
    '4': { value: { base: '{colors.red.light.400}', _dark: '{colors.red.dark.200}' } },
    '5': { value: { base: '{colors.red.light.500}', _dark: '{colors.red.dark.500}' } },
    '6': { value: { base: '{colors.red.light.600}', _dark: '{colors.red.dark.600}' } },
    '7': { value: { base: '{colors.red.light.700}', _dark: '{colors.red.dark.900}' } },
    '8': { value: { base: '{colors.red.light.800}', _dark: '{colors.red.dark.800}' } },
    '9': { value: { base: '{colors.red.light.900}', _dark: '{colors.red.dark.700}' } },
    '10': { value: { base: '{colors.red.light.1000}', _dark: '{colors.red.dark.1000}' } },
    '11': { value: { base: '{colors.red.light.1100}', _dark: '{colors.red.dark.1100}' } },
    '12': { value: { base: '{colors.red.light.1200}', _dark: '{colors.red.dark.1200}' } },
    a1: { value: { base: '{colors.red.light.a100}', _dark: '{colors.red.dark.a100}' } },
    a2: { value: { base: '{colors.red.light.a200}', _dark: '{colors.red.dark.a200}' } },
    a3: { value: { base: '{colors.red.light.a300}', _dark: '{colors.red.dark.a300}' } },
  },
};
