/**
 * GOES 테마 구버전 numeric scale (brand / success / warning / error / info / accent).
 * 신규 role-based 체계로 전환 완료 후 본 파일을 제거하면 구 토큰을 일괄 정리할 수 있다.
 */
export const goesLegacy = {
  success: {
    '1': { value: { base: '{colors.goes.green.light.100}', _dark: '{colors.goes.green.light.100}' } },
    '2': { value: { base: '{colors.goes.green.light.200}', _dark: '{colors.goes.green.light.200}' } },
    '3': { value: { base: '{colors.goes.green.light.300}', _dark: '{colors.goes.green.light.300}' } },
    '4': { value: { base: '{colors.goes.green.light.400}', _dark: '{colors.goes.green.light.400}' } },
    '5': { value: { base: '{colors.goes.green.light.500}', _dark: '{colors.goes.green.light.500}' } },
    '6': { value: { base: '{colors.goes.green.light.600}', _dark: '{colors.goes.green.light.600}' } },
    '7': { value: { base: '{colors.goes.green.light.700}', _dark: '{colors.goes.green.light.900}' } },
    '8': { value: { base: '{colors.goes.green.light.800}', _dark: '{colors.goes.green.light.800}' } },
    '9': { value: { base: '{colors.goes.green.light.900}', _dark: '{colors.goes.green.light.700}' } },
    '10': { value: { base: '{colors.goes.green.light.1000}', _dark: '{colors.goes.green.light.1000}' } },
    '11': { value: { base: '{colors.goes.green.light.1100}', _dark: '{colors.goes.green.light.1100}' } },
    '12': { value: { base: '{colors.goes.green.light.1200}', _dark: '{colors.goes.green.light.1200}' } },
    a1: { value: { base: '{colors.goes.green.light.a100}', _dark: '{colors.goes.green.light.a100}' } },
    a2: { value: { base: '{colors.goes.green.light.a200}', _dark: '{colors.goes.green.light.a200}' } },
    a3: { value: { base: '{colors.goes.green.light.a300}', _dark: '{colors.goes.green.light.a300}' } },
  },
  warning: {
    '1': { value: { base: '{colors.goes.orange.light.100}', _dark: '{colors.goes.orange.light.100}' } },
    '2': { value: { base: '{colors.goes.orange.light.200}', _dark: '{colors.goes.orange.light.200}' } },
    '3': { value: { base: '{colors.goes.orange.light.300}', _dark: '{colors.goes.orange.light.300}' } },
    '4': { value: { base: '{colors.goes.orange.light.400}', _dark: '{colors.goes.orange.light.400}' } },
    '5': { value: { base: '{colors.goes.orange.light.500}', _dark: '{colors.goes.orange.light.500}' } },
    '6': { value: { base: '{colors.goes.orange.light.600}', _dark: '{colors.goes.orange.light.600}' } },
    '7': { value: { base: '{colors.goes.orange.light.700}', _dark: '{colors.goes.orange.light.900}' } },
    '8': { value: { base: '{colors.goes.orange.light.800}', _dark: '{colors.goes.orange.light.800}' } },
    '9': { value: { base: '{colors.goes.orange.light.900}', _dark: '{colors.goes.orange.light.700}' } },
    '10': { value: { base: '{colors.goes.orange.light.1000}', _dark: '{colors.goes.orange.light.1000}' } },
    '11': { value: { base: '{colors.goes.orange.light.1100}', _dark: '{colors.goes.orange.light.1100}' } },
    '12': { value: { base: '{colors.goes.orange.light.1200}', _dark: '{colors.goes.orange.light.1200}' } },
    a1: { value: { base: '{colors.goes.orange.light.a100}', _dark: '{colors.goes.orange.light.a100}' } },
    a2: { value: { base: '{colors.goes.orange.light.a200}', _dark: '{colors.goes.orange.light.a200}' } },
    a3: { value: { base: '{colors.goes.orange.light.a300}', _dark: '{colors.goes.orange.light.a300}' } },
  },
  error: {
    '1': { value: { base: '{colors.goes.red.light.100}', _dark: '{colors.goes.red.light.100}' } },
    '2': { value: { base: '{colors.goes.red.light.200}', _dark: '{colors.goes.red.light.200}' } },
    '3': { value: { base: '{colors.goes.red.light.300}', _dark: '{colors.goes.red.light.300}' } },
    '4': { value: { base: '{colors.goes.red.light.400}', _dark: '{colors.goes.red.light.400}' } },
    '5': { value: { base: '{colors.goes.red.light.500}', _dark: '{colors.goes.red.light.500}' } },
    '6': { value: { base: '{colors.goes.red.light.600}', _dark: '{colors.goes.red.light.600}' } },
    '7': { value: { base: '{colors.goes.red.light.700}', _dark: '{colors.goes.red.light.900}' } },
    '8': { value: { base: '{colors.goes.red.light.800}', _dark: '{colors.goes.red.light.800}' } },
    '9': { value: { base: '{colors.goes.red.light.900}', _dark: '{colors.goes.red.light.700}' } },
    '10': { value: { base: '{colors.goes.red.light.1000}', _dark: '{colors.goes.red.light.1000}' } },
    '11': { value: { base: '{colors.goes.red.light.1100}', _dark: '{colors.goes.red.light.1100}' } },
    '12': { value: { base: '{colors.goes.red.light.1200}', _dark: '{colors.goes.red.light.1200}' } },
    a1: { value: { base: '{colors.goes.red.light.a100}', _dark: '{colors.goes.red.light.a100}' } },
    a2: { value: { base: '{colors.goes.red.light.a200}', _dark: '{colors.goes.red.light.a200}' } },
    a3: { value: { base: '{colors.goes.red.light.a300}', _dark: '{colors.goes.red.light.a300}' } },
  },
  info: {
    '1': { value: { base: '{colors.goes.violet.light.100}', _dark: '{colors.goes.violet.light.100}' } },
    '2': { value: { base: '{colors.goes.violet.light.200}', _dark: '{colors.goes.violet.light.200}' } },
    '3': { value: { base: '{colors.goes.violet.light.300}', _dark: '{colors.goes.violet.light.300}' } },
    '4': { value: { base: '{colors.goes.violet.light.400}', _dark: '{colors.goes.violet.light.400}' } },
    '5': { value: { base: '{colors.goes.violet.light.500}', _dark: '{colors.goes.violet.light.500}' } },
    '6': { value: { base: '{colors.goes.violet.light.600}', _dark: '{colors.goes.violet.light.600}' } },
    '7': { value: { base: '{colors.goes.violet.light.700}', _dark: '{colors.goes.violet.light.900}' } },
    '8': { value: { base: '{colors.goes.violet.light.800}', _dark: '{colors.goes.violet.light.800}' } },
    '9': { value: { base: '{colors.goes.violet.light.900}', _dark: '{colors.goes.violet.light.700}' } },
    '10': { value: { base: '{colors.goes.violet.light.1000}', _dark: '{colors.goes.violet.light.1000}' } },
    '11': { value: { base: '{colors.goes.violet.light.1100}', _dark: '{colors.goes.violet.light.1100}' } },
    '12': { value: { base: '{colors.goes.violet.light.1200}', _dark: '{colors.goes.violet.light.1200}' } },
    a1: { value: { base: '{colors.goes.violet.light.a100}', _dark: '{colors.goes.violet.light.a100}' } },
    a2: { value: { base: '{colors.goes.violet.light.a200}', _dark: '{colors.goes.violet.light.a200}' } },
    a3: { value: { base: '{colors.goes.violet.light.a300}', _dark: '{colors.goes.violet.light.a300}' } },
  },
  brand: {
    '1': { value: { base: '{colors.goes.light.100}', _dark: '{colors.goes.light.100}' } },
    '2': { value: { base: '{colors.goes.light.200}', _dark: '{colors.goes.light.200}' } },
    '3': { value: { base: '{colors.goes.light.300}', _dark: '{colors.goes.light.300}' } },
    '4': { value: { base: '{colors.goes.light.400}', _dark: '{colors.goes.light.400}' } },
    '5': { value: { base: '{colors.goes.light.500}', _dark: '{colors.goes.light.500}' } },
    '6': { value: { base: '{colors.goes.light.600}', _dark: '{colors.goes.light.600}' } },
    '7': { value: { base: '{colors.goes.light.700}', _dark: '{colors.goes.light.900}' } },
    '8': { value: { base: '{colors.goes.light.800}', _dark: '{colors.goes.light.800}' } },
    '9': { value: { base: '{colors.goes.light.900}', _dark: '{colors.goes.light.700}' } },
    '10': { value: { base: '{colors.goes.light.1000}', _dark: '{colors.goes.light.1000}' } },
    '11': { value: { base: '{colors.goes.light.1100}', _dark: '{colors.goes.light.1100}' } },
    '12': { value: { base: '{colors.goes.light.1200}', _dark: '{colors.goes.light.1200}' } },
    a1: { value: { base: '{colors.goes.light.a100}', _dark: '{colors.goes.light.a100}' } },
    a2: { value: { base: '{colors.goes.light.a200}', _dark: '{colors.goes.light.a200}' } },
    a3: { value: { base: '{colors.goes.light.a300}', _dark: '{colors.goes.light.a300}' } },
  },
  accent: {
    purple: {
      '1': { value: { base: '{colors.goes.violet.light.100}', _dark: '{colors.goes.violet.light.100}' } },
      '2': { value: { base: '{colors.goes.violet.light.200}', _dark: '{colors.goes.violet.light.200}' } },
      '3': { value: { base: '{colors.goes.violet.light.300}', _dark: '{colors.goes.violet.light.300}' } },
      '4': { value: { base: '{colors.goes.violet.light.400}', _dark: '{colors.goes.violet.light.400}' } },
      '5': { value: { base: '{colors.goes.violet.light.500}', _dark: '{colors.goes.violet.light.500}' } },
      '6': { value: { base: '{colors.goes.violet.light.600}', _dark: '{colors.goes.violet.light.600}' } },
      '7': { value: { base: '{colors.goes.violet.light.700}', _dark: '{colors.goes.violet.light.900}' } },
      '8': { value: { base: '{colors.goes.violet.light.800}', _dark: '{colors.goes.violet.light.800}' } },
      '9': { value: { base: '{colors.goes.violet.light.900}', _dark: '{colors.goes.violet.light.700}' } },
      '10': { value: { base: '{colors.goes.violet.light.1000}', _dark: '{colors.goes.violet.light.1000}' } },
      '11': { value: { base: '{colors.goes.violet.light.1100}', _dark: '{colors.goes.violet.light.1100}' } },
      '12': { value: { base: '{colors.goes.violet.light.1200}', _dark: '{colors.goes.violet.light.1200}' } },
      a1: { value: { base: '{colors.goes.violet.light.a100}', _dark: '{colors.goes.violet.light.a100}' } },
      a2: { value: { base: '{colors.goes.violet.light.a200}', _dark: '{colors.goes.violet.light.a200}' } },
      a3: { value: { base: '{colors.goes.violet.light.a300}', _dark: '{colors.goes.violet.light.a300}' } },
    },
  },
} as const;
