import type { ColorToken } from './type';

export const mui: ColorToken = {
  stroke: {
    school: { value: 'hsla(139, 64%, 79%, 1)' },
    mildang: { value: 'hsla(237, 100%, 89%, 1)' },
  },
  snackbar: { value: '#2B2D36' },
  activeRating: { value: '#FBCB2D' },
  divider: { value: '#EDEDF0' },
  primary: {
    dark: { value: '#2B2D36' },
    darkActive: { value: '#15171B' },
    darkHover: { value: '#202228' },
    main: { value: '#2B2D36' },
    stroke: { value: '#E4E4E7' },
    strokeHover: { value: '#D5D5D7' },
    lightHover: { value: '#F7F7FA' },
    lightActive: { value: '#EDEDF0' },
    light: { value: '#FFFFFF' },
    contrastText: { value: '#FFFFFF' },
  },
  secondary: {
    dark: { value: '#1C9241' },
    darkActive: { value: '#20A64A' },
    darkHover: { value: '#24BB54' },
    main: { value: '#28D05D' },
    stroke: { value: '#A9ECBE' },
    strokeHover: { value: '#7EE39E' },
    lightActive: { value: '#D4F6DF' },
    lightHover: { value: '#E9FAEF' },
    light: { value: '#F2FCF5' },
    contrastText: { value: '#FFFFFF' },
  },
  error: {
    dark: { value: '#B33842' },
    darkActive: { value: '#CC404C' },
    darkHover: { value: '#E54855' },
    main: { value: '#FF505F' },
    stroke: { value: '#FFB9BF' },
    strokeHover: { value: '#FF969F' },
    lightHover: { value: '#FFEDEF' },
    lightActive: { value: '#FFDCDF' },
    light: { value: '#FFF4F5' },
    contrastText: { value: '#FFFFFF' },
  },
  warning: {
    dark: { value: '#B36A00' },
    darkActive: { value: '#CC7A00' },
    darkHover: { value: '#E58900' },
    main: { value: '#FF9800' },
    stroke: { value: '#FFD699' },
    strokeHover: { value: '#FFC166' },
    lightActive: { value: '#FFEACC' },
    lightHover: { value: '#FFF5E5' },
    light: { value: '#FFF9F0' },
    contrastText: { value: '#FFFFFF' },
  },
  info: {
    dark: { value: '#0058B3' },
    darkActive: { value: '#0064CC' },
    darkHover: { value: '#0070E5' },
    main: { value: '#007DFF' },
    stroke: { value: '#99CBFF' },
    strokeHover: { value: '#66B1FF' },
    lightActive: { value: '#CCE5FF' },
    lightHover: { value: '#E5F2FF' },
    light: { value: '#E5F2FF' },
    contrastText: { value: '#FFFFFF' },
  },
  text: {
    primary: { value: '#2B2D36' },
    secondary: { value: '#55575E' },
    tertiary: { value: '#86878C' },
  },
  background: {
    primary: { value: '#FFFFFF' },
    secondary: { value: '#F7F7FA' },
    tertiary: { value: '#EDEDF0' },
    default: { value: 'rgba(255, 255, 255, 1)' },
  },
};
